export const ALGERIAN_WILAYAS = [
  { value: "01", label: "01 أدرار | Adrar" },
  { value: "02", label: "02 الشلف | Chlef" },
  { value: "03", label: "03 الأغواط | Laghouat" },
  { value: "04", label: "04 أم البواقي | Oum El Bouaghi" },
  { value: "05", label: "05 باتنة | Batna" },
  { value: "06", label: "06 بجاية | Béjaïa" },
  { value: "07", label: "07 بسكرة | Biskra" },
  { value: "08", label: "08 بشار | Béchar" },
  { value: "09", label: "09 البليدة | Blida" },
  { value: "10", label: "10 البويرة | Bouira" },
  { value: "11", label: "11 تمنراست | Tamanrasset" },
  { value: "12", label: "12 تبسة | Tébessa" },
  { value: "13", label: "13 تلمسان | Tlemcen" },
  { value: "14", label: "14 تيارت | Tiaret" },
  { value: "15", label: "15 تيزي وزو | Tizi Ouzou" },
  { value: "16", label: "16 الجزائر | Alger" },
  { value: "17", label: "17 الجلفة | Djelfa" },
  { value: "18", label: "18 جيجل | Jijel" },
  { value: "19", label: "19 سطيف | Sétif" },
  { value: "20", label: "20 سعيدة | Saïda" },
  { value: "21", label: "21 سكيكدة | Skikda" },
  { value: "22", label: "22 سيدي بلعباس | Sidi Bel Abbès" },
  { value: "23", label: "23 عنابة | Annaba" },
  { value: "24", label: "24 قالمة | Guelma" },
  { value: "25", label: "25 قسنطينة | Constantine" },
  { value: "26", label: "26 المدية | Médéa" },
  { value: "27", label: "27 مستغانم | Mostaganem" },
  { value: "28", label: "28 المسيلة | M'sila" },
  { value: "29", label: "29 معسكر | Mascara" },
  { value: "30", label: "30 ورقلة | Ouargla" },
  { value: "31", label: "31 وهران | Oran" },
  { value: "32", label: "32 البيض | El Bayadh" },
  { value: "33", label: "33 إليزي | Illizi" },
  { value: "34", label: "34 برج بوعريريج | Bordj Bou Arréridj" },
  { value: "35", label: "35 بومرداس | Boumerdès" },
  { value: "36", label: "36 الطارف | El Tarf" },
  { value: "37", label: "37 تندوف | Tindouf" },
  { value: "38", label: "38 تيسمسيلت | Tissemsilt" },
  { value: "39", label: "39 الوادي | El Oued" },
  { value: "40", label: "40 خنشلة | Khenchela" },
  { value: "41", label: "41 سوق أهراس | Souk Ahras" },
  { value: "42", label: "42 تيبازة | Tipaza" },
  { value: "43", label: "43 ميلة | Mila" },
  { value: "44", label: "44 عين الدفلى | Aïn Defla" },
  { value: "45", label: "45 النعامة | Naâma" },
  { value: "46", label: "46 عين تموشنت | Aïn Témouchent" },
  { value: "47", label: "47 غرداية | Ghardaïa" },
  { value: "48", label: "48 غليزان | Relizane" },
  { value: "49", label: "49 تيميمون | Timimoun" },
  { value: "50", label: "50 برج باجي مختار | Bordj Badji Mokhtar" },
  { value: "51", label: "51 أولاد جلال | Ouled Djellal" },
  { value: "52", label: "52 بني عباس | Béni Abbès" },
  { value: "53", label: "53 عين صالح | In Salah" },
  { value: "54", label: "54 عين قزام | In Guezzam" },
  { value: "55", label: "55 تقرت | Touggourt" },
  { value: "56", label: "56 جانت | Djanet" },
  { value: "57", label: "57 المغير | El M'Ghair" },
  { value: "58", label: "58 المنيعة | El Meniaa" }
];

export const BUSINESS_TYPES = [
  { value: "commercant", label: "Commerçant — تاجر" },
  { value: "artisan", label: "Artisan — حرفي" },
  { value: "fellah", label: "Fellah/Éleveur — فلاح/ مربي" }
];

export const TRUCK_MODELS = [
  { value: "3.5", label: "Camion 3.5 tonnes - شاحنة 3,5 طن" },
  { value: "6", label: "Camion 6 tonnes - شاحنة 6 طن" }
];
